
package itson.org.proyectografos.presentacion;

import itson.org.proyectografos.CargadorDatos;
import itson.org.proyectografos.Carretera;
import itson.org.proyectografos.Controlador;
import itson.org.proyectografos.Localidad;
import itson.org.proyectografos.PanelMapa;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author oliro
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    private Controlador control;
    
    private PanelMapa panelMapa;
    private List<Localidad> localidades;
    private List<Carretera> carreteras;
    
    public VentanaPrincipal(Controlador control) {
        this.control = control;
        initComponents();

        // Cargamos los datos de Chiapas
        this.localidades = CargadorDatos.cargarLocalidades();
        this.carreteras = CargadorDatos.cargarCarreteras(this.localidades);

        // Inicializamos el panel con los datos reales
        panelMapa = new PanelMapa(this.localidades, this.carreteras);

        // Agregamos al centro de la ventana
        this.add(panelMapa, java.awt.BorderLayout.CENTER);
        this.revalidate();
    }

    private void inicializarDatosMock() {
        localidades = new ArrayList<>();
        carreteras = new ArrayList<>();

        // NOTA: Estas coordenadas (X, Y) son FICTICIAS. 
        // Deberán ajustarlas para que coincidan con los puntos reales en SU imagen de mapa.
        Localidad tuxtla = new Localidad("Tuxtla G.", 300, 400);
        Localidad tapachula = new Localidad("Tapachula", 700, 700);
        Localidad sanCristobal = new Localidad("San Cristóbal", 500, 450);
        Localidad comitan = new Localidad("Comitán", 650, 550);
        Localidad palenque = new Localidad("Palenque", 800, 200);

        localidades.add(tuxtla);
        localidades.add(tapachula);
        localidades.add(sanCristobal);
        localidades.add(comitan);
        localidades.add(palenque);

        // Carreteras aproximadas
//        carreteras.add(new Carretera(tuxtla, sanCristobal));
//        carreteras.add(new Carretera(sanCristobal, comitan));
//        carreteras.add(new Carretera(tuxtla, tapachula)); // Costera aprox
//        carreteras.add(new Carretera(sanCristobal, palenque));
    }
    
    private void iniciarSimulacion() {
        new Thread(() -> {
            try {
                // Paso 1: Reseteamos colores
                for(Localidad l : localidades) l.colorActual = new Color(0, 100, 255, 200);
                for(Carretera c : carreteras) c.colorActual = new Color(100, 100, 100, 150);
                panelMapa.repaint();
                Thread.sleep(1000);

                // Paso 2: Visitamos Tuxtla
                Localidad tuxtla = localidades.get(0);
                tuxtla.colorActual = Color.RED; // Color de 'visitado'
                panelMapa.repaint();
                Thread.sleep(800);

                // Paso 3: Recorremos la carretera Tuxtla -> San Cristóbal
                Carretera c1 = carreteras.get(0);
                c1.colorActual = Color.GREEN; // Color de 'activo'
                c1.grosor = 6;
                panelMapa.repaint();
                Thread.sleep(800);

                // Paso 4: Llegamos a San Cristóbal
                Localidad sc = localidades.get(2);
                sc.colorActual = Color.RED;
                panelMapa.repaint();
                Thread.sleep(800);

            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuLateral = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnSimular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 231, 206));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        panelMenuLateral.setBackground(new java.awt.Color(236, 231, 206));
        panelMenuLateral.setForeground(new java.awt.Color(236, 231, 206));
        panelMenuLateral.setPreferredSize(new java.awt.Dimension(200, 400));

        panelBotones.setOpaque(false);
        panelBotones.setPreferredSize(new java.awt.Dimension(180, 100));

        btnSimular.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSimular.setText("Simular");
        btnSimular.setPreferredSize(new java.awt.Dimension(180, 30));
        btnSimular.addActionListener(this::btnSimularActionPerformed);

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSimular, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addComponent(btnSimular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 22));

        javax.swing.GroupLayout panelMenuLateralLayout = new javax.swing.GroupLayout(panelMenuLateral);
        panelMenuLateral.setLayout(panelMenuLateralLayout);
        panelMenuLateralLayout.setHorizontalGroup(
            panelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMenuLateralLayout.setVerticalGroup(
            panelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLateralLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenuLateral, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        iniciarSimulacion();
    }//GEN-LAST:event_btnSimularActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelMenuLateral;
    // End of variables declaration//GEN-END:variables
}
